# vim: ft=xf86conf

Section "Device"
    Identifier    "IntelGPU"
    Driver        "intel"
    Option        "TearFree"
EndSection

Section "Monitor"
    Identifier    "Monitor0"
    Option        "DPMS"
EndSection

Section "Screen"
    Identifier    "Screen0"
    Device        "IntelGPU"
    Monitor       "Monitor0"
EndSection
