# https://khard.readthedocs.io/
# vim: ft=dosini

[addressbooks]
[[family]]
path = ~/dox/files/contacts/family/
[[friends]]
path = ~/dox/files/contacts/friends/
[[acquantances]]
path = ~/dox/files/contacts/acquaintances/
[[job]]
path = ~/dox/files/contacts/job/
[[services]]
path = ~/dox/files/contacts/services/

[general]
default_action = list
