#!/bin/sh

read file

case "$1" in
    "w") setwall "$file" & ;;
    "p") wal -ni "$file" & ;;
    "c") copyimage "$file" & ;;
    "n") newname=$(echo "$file" | dmenu -p "Enter new file name") && mv "$file" "$newname" && notify-send "Moved '$file' to '$newname'" ;;
    "r") convert -rotate 90 "$file" "$file" ;;
    "R") convert -rotate -90 "$file" "$file" ;;
    "f") convert -flop "$file" "$file" ;;
    "y") echo -n "$file" | xclip -selection clipboard && notify-send "Copied to clipboard" "$file" & ;;
    "Y") echo -n "$(readlink -f "$file")" | xclip -selection clipboard && notify-send "Copied to clipboard" "$(readlink -f "$file")" & ;;
    "d") ([ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted.") & ;;
esac
