#!/usr/bin/env bash

FILE_PATH="${1}"
MIMETYPE="$(file --dereference --brief --mime-type -- "${FILE_PATH}")"

case "${MIMETYPE}" in
    text/* | */xml)
        highlight --replace-tabs=2 --out-format=ansi -- "${FILE_PATH}" 2>/dev/null && exit
        cat "${FILE_PATH}" && exit
esac

echo '----- File Type Classification -----' && file --dereference -- "${FILE_PATH}"
