#!/usr/bin/env bash
readonly ID_PREVIEW="preview"

if [ -e "$FIFO_UEBERZUG" ]; then
	if [[ "$1" == "draw" ]]; then

		declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
			[x]="$2" [y]="$3" [max_width]="$4" [max_height]="$5"
			[path]="${PWD}/$6") >"$FIFO_UEBERZUG"

	elif [[ "$1" == "videopreview" ]]; then
		[[ ! -f "/tmp/$6.png" ]] && ffmpegthumbnailer -i "${PWD}/$6" -o "/tmp/$6.png" -s 0 -q 10

		declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
			[x]="$2" [y]="$3" [max_width]="$4" [max_height]="$5"
			[path]="/tmp/$6.png") >"$FIFO_UEBERZUG"

	elif [[ "$1" == "pdf" ]]; then
		[[ ! -f "/tmp/$6.png" ]] && pdftoppm -f 1 -l 1 \
			-scale-to-x 1920 -scale-to-y -1 -singlefile \
			-jpeg -tiffcompression jpeg -- "${PWD}/$6" "/tmp/$6"

		declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
			[x]="$2" [y]="$3" [max_width]="$4" [max_height]="$5"
			[path]="/tmp/$6.jpg") >"$FIFO_UEBERZUG"


	elif [[ "$1" == "djvu" ]]; then
		[[ ! -f "/tmp/$6.jpg" ]] && ddjvu "${PWD}/$6" -page=1 -format=ppm | convert - "/tmp/$6.jpg"

		declare -p -A cmd=([action]=add [identifier]="$ID_PREVIEW"
			[x]="$2" [y]="$3" [max_width]="$4" [max_height]="$5"
			[path]="/tmp/$6.jpg") >"$FIFO_UEBERZUG"

	elif [[ "$1" == "clear" ]]; then
		declare -p -A cmd=([action]=remove [identifier]="$ID_PREVIEW") \
			>"$FIFO_UEBERZUG"
	fi
fi
