#!/bin/sh

while read -r file; do
set -x
    case "$1" in
        "w") set-wallpaper.sh "$file" & ;;
        "l") set-wallpaper.sh "$file" lock & ;;
        "c") copy-image.sh "$file" & ;;
        "m") newname=$(echo "$file" | dmenu -p "Enter new file name") && mv "$file" "$newname" && notify-send "Moved '$file' to '$newname'" ;;
        "r") magick "$file" -rotate 90 "$file" ;;
        "R") magick "$file" -rotate -90 "$file" ;;
        "f") magick "$file" -flop "$file" ;;
        "n") magick "$file" -channel RGB -negate "$file" ;;
        "y") printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard && notify-send "Copied to clipboard" "$file" & ;;
        "Y") readlink -f "$file" | tr -d '\n' | xclip -selection clipboard && notify-send "Copied to clipboard" "$(readlink -f "$file")" & ;;
        "d") ([ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted.") & ;;
        "g") dragon "$file" & ;;
        "e") gimp "$file" & ;;
        "i") notify-send "File information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")" ;;
    esac
done
