#!/bin/bash

dunst &
picom &
sxhkd &

sleep 3 && exec polybar -r notebar &

xset r rate 200 35
xsetroot -cursor_name left_ptr
xwallpaper --stretch "$XDG_DATA_HOME/wallpaper"

/usr/bin/vmware-user &

exec dwm
