#!/bin/sh

# colors
alias \
    ls='ls --color=auto --group-directories-first' \
    grep='grep --color=auto'

# fast ls
alias \
    la='ls -a' \
    ll='ls -lsh' \
    l='ls -lash'

# progs
alias \
    v='$EDITOR' \
    sv='sudo $EDITOR' \
    sp='sudo pacman' \
    sc='systemctl' \
    ssc='sudo systemctl' \
    fm='vifmrun' \
    nb='newsboat -q' \
    nbr='newsboat -qr' \
    yt='youtube-viewer' \
    cl='calcurse' \
    mkd='mkdir -pv' \
    smkd='sudo mkdir -pv' \
    rst='reset && source ~/.bashrc && stty echo && tput cvvis' \
    cp='cp -r' \
    rm='rm -r' \
    sql='sqlite3' \
    p3='python3' \
    ff='ffplay -autoexit -nodisp' \
    shr='cd $XDG_DATA_HOME' \
    sm='sc-im'

# git
alias \
    dg='/usr/bin/git --git-dir="$HOME/Documents/dotfiles" --work-tree="$HOME"' \
    gst='git status' \
    gd='git diff' \
    gds='git diff --staged' \
    ga='git add' \
    gc='git commit' \
    gps='git push' \
    gpl='git pull' \
    gl='git log --oneline --graph --branches' \
    glo='git log --oneline --graph' \
    grh='git reset HEAD' \
    gb='git branch' \
    gch='git checkout' \
    gr='git remote' \
    gsh='git stash' \
    gcp='git cherry-pick' \
    grs='git reset'

# files
alias \
    va='$EDITOR ~/.config/aliases' \
    vb='$EDITOR ~/.bashrc' \
    vv='$EDITOR ~/.vimrc' \
    vp='$EDITOR ~/.profile' \
    vg='$EDITOR .gitignore' \
    v3='$EDITOR ~/.config/i3/config' \
    vf='$EDITOR ~/.config/vifm/vifmrc' \
    vx='$EDITOR ~/.config/xprofile'

# directories
alias \
    scr='cd ~/.local/scripts/ && ls' \
    med='cd ~/Media/ && ls' \
    wrk='cd ~/Work/ && ls' \
    gop='cd $GOPATH/src/ && ls' \
    ltx='cd ~/Work/latex/ && ls'

# completions for aliases
completions="/usr/share/bash-completion/completions"
# systemctl
. $completions/systemctl
complete -F _systemctl systemctl sc ssc
# pacman
. $completions/pacman
complete -F _pacman pacman sp
# git
. $completions/git
__git_complete gd _git_diff
__git_complete ga _git_add
__git_complete gb _git_branch
__git_complete gc _git_commit
__git_complete gr _git_remote
__git_complete gch _git_checkout
__git_complete gps _git_push
__git_complete gpl _git_pull
__git_complete grs _git_reset
