#!/bin/sh

dunst &
compton --invert-color-include "class_i%=\"*_inverted_*\"" &
# wal -Rn &
unclutter &
sxhkd &

setwall &
# timewall &

redshift &
safeeyes &

i3mpdupdate &

xmodmap -e "keycode 135 = Super_R Menu"
xset r rate 200 35
xrdb -merge "$HOME/.Xresources"
