#! /bin/sh

bspc rule -r "*"

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

pkill polybar
polybar -r notebar &

bspc config border_width 2
bspc config window_gap   3

bspc rule -a dropdown state=floating

bspc rule -a "Slack" desktop=^8
bspc rule -a "TelegramDesktop" desktop=^9
