#! /bin/sh

bspc rule -r "*"
pkill polybar

monitors=`xrandr --listmonitors | wc -l`
if [ $monitors -eq 2 ]; then
    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
    polybar -r notebar &
else
    bspc monitor HDMI2 -d I II III IV V
    bspc monitor DP2   -d VI VII VIII IX X

    polybar -r horizontal &
    polybar -r vertical &
fi

bspc config focus_follows_pointer true
bspc config border_width 2
bspc config window_gap 3

bspc rule -a dropdown state=floating
bspc rule -a Zathura state=tiled

bspc rule -a "Slack" desktop=^8
bspc rule -a "VK" desktop=^8
bspc rule -a "TelegramDesktop" desktop=^9
