#!/bin/sh

usage="Usage: ${0##*/} [-h] [-l] [-s syntax] [file]
If file not specified, STDIN used.

-h — show help
-s — specify syntax
-l — output to less
"

warning="Specify syntax type via -s option"
use_less="false"
use_stdin="false"

while getopts "hls:" opt; do
	case $opt in
		h) printf "$usage" && exit ;;
		s) syntax=$OPTARG ;;
		l) use_less="true" ;;
		*) echo "$usage" && exit 1 ;;
	esac
done

shift $(($OPTIND - 1))
file=$1

if [ -z $file ]; then
	use_stdin="true"
	[ ! -t 0 ] && lines=$(</dev/stdin)
fi

command="highlight --out-format=ansi"
[ ! -z "$syntax" ] && command="$command --syntax=$syntax"

if [ "$use_stdin" = "false" ]; then
	text="$($command $1 2>/dev/null)"
else
	text="$(echo -e "$lines" | $command 2>/dev/null)"
	[ "$?" -ne "0" ] && [ -z "$syntax" ] && echo "$warning" && exit 1
fi


if [ $use_less = "true" ]; then
	echo -e "$text" | less -r
else
	echo -e "$text"
fi
