#!/bin/bash

pgrep -x dmenu && exit

items="vifm
ncmpcpp
calcurse
python
htop
tmux"

program=$(echo -e -n "$items" | dmenu -i -p "Run dropdown:")
[ "$?" -ne "0" ] && exit
[ "$program" = "python" -o "$program" = "ncmpcpp" ] && program="$program -q"
[ "$program" = "vifm" ] && program="vifmrun"
exec $TERMINAL -n "${TERMINAL}_dropdown_" $program
