#!/bin/bash

# pgrep "${0##*/}" | [ $(wc -l) -gt 2 ] && exit 0

folder1="databases-incognito"
folder2="VideoDecodeStats"

function check_and_remove {
	[ -d "$HOME/$folder1" ] && rm -rf "$HOME/$folder1"
	[ -d "$HOME/$folder2" ] && rm -rf "$HOME/$folder2"
}

check_and_remove

inotifywait -qme create $HOME &>>/dev/null | while true
do
	check_and_remove
done
