#!/bin/bash

ERROR=$((youtube-dl -F "$1" 3>&2 2>&1 1>&3) 2>/dev/null)
[[ "$?" -ne "0" ]] && notify-send "Youtube-dl error" "$ERROR" && exit 1
mpv -quiet --ytdl-format="bestvideo[height<=1080]+bestaudio/best[height<=1080]" "$1" >/dev/null 2>&1
