#!/bin/bash

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"

cd "$dir" || exit

case "$file" in
    *\.cpp) g++ -g -O0 -Wall -Wextra -pedantic -o "$base" "$file" ;;
    *\.ms) groff -ms "$file" ${@:2} -T pdf > "$base".pdf ;;
    *\.py) python3 "$1" ${@:2} ;;
    *\.md) pandoc "$file" --pdf-engine=xelatex ${@:2} -o "$base".pdf ;;
    *\.tex) xelatex ${@:2} "$file" ;;
    *\.go) go run "$file" ${@:2} ;;
    *\.html) $BROWSER "$file" ;;
    *\.js) node "$file" ;;
    *\.Xresources) xrdb -merge "$file" ;;
    *config\.h) make && sudo make install ;;
    *) sed 1q "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ${@:2} ;;
esac

# beamer: -t beamer
# russian markdown: 
