#!/bin/sh

possible_items="xcompmgr\nflameshot\ntelegram-desktop\nvk"
for item in `echo -e $possible_items`; do pgrep -x $item >/dev/null && items="$item\n$items" ; done

item=$(echo -e $items | dmenu -i -p "Which one to kill?")
[[ "$?" -eq "1" ]] && exit 1
killall $item
[[ "$?" -eq "0" ]] && notify-send "$item killed" && exit 0
notify-send "Error while killing $item" && exit 1
