#!/bin/bash

memory_file="$HOME/Services/NEET/memory"
log_file="$HOME/Services/NEET/log"

ntime=$(date "+%R")
ndate=$(date "+%F")

if [ -f "$memory_file" ]; then
    read -d '\n' minutes cdate ctime <$memory_file
else
    echo "0" > $memory_file
    echo "$ndate" >> $memory_file
    echo "$ntime" >> $memory_file
    exit
fi

nabstime=$((${ntime%:*} * 60 + ${ntime#*:} ))
cabstime=$((${ctime%:*} * 60 + ${ctime#*:} ))

if [ "$ndate" != "$cdate" ] || [ $(($nabstime - $cabstime)) -le 1 ]; then
    echo "$cdate, $ctime -> $minutes" >> "$log_file"
    echo "0" > $memory_file
    echo "$ndate" >> $memory_file
    echo "$ntime" >> $memory_file
else
    echo $(($nabstime - $cabstime)) > "$memory_file"
    echo "$ndate" >> $memory_file
    echo "$ctime" >> $memory_file
fi
