#!/bin/bash

pgrep -x dmenu && exit

items="vifmrun
ncmpcpp
calcurse
python
htop
tmux"

program=$(echo -e -n "$items" | dmenu -i -p "Run dropdown:")
[ "$?" -ne "0" ] && exit
[ "$program" = "python" -o "$program" = "ncmpcpp" ] && program="$program -q"
exec $TERMINAL -n dropdown $program
