#!/bin/sh

options="xcompmgr
compton
nm-applet
qbittorrent
transmission-da
qutebrowser
safeeyes
flameshot
telegram
vk"

for item in `echo -e $options`; do pgrep "$item" >/dev/null && items="$item\n$items" ; done

item=$(echo -e $items | dmenu -i -p "Which one to kill?")
[[ "$?" -eq "1" ]] && exit 1
[[ -z $item ]] && exit 1
pkill --signal 9 "$item"
[[ "$?" -eq "0" ]] && notify-send "$item terminated" && exit 0
notify-send "Error while terminating $item" && exit 1
