#!/bin/bash

[ $(pgrep -x hibernator | wc -l) -gt 2 ] && exit 1

low_message="Low battery"
critical_message="Critical battery"
remain_time=15

acpi -b | awk -F'[,:%]' '{print $2, $3}' | {
	read -r status capacity
	if [ "$status" = "Discharging" ]; then
		if [ "$capacity" -le 5  ]; then
			notify-send -u critical -t 14000 "$critical_message" "$status ${capacity}% \nRemain time: $remain_time sec"
			sleep $remain_time
			read -r new_status new_capacity < <(acpi -b | awk -F'[,:%]' '{print $2, $3}')
			[ "$new_status" = "Discharging" -a "$new_capacity" -le 5  ] && sudo systemctl hibernate
		elif [ "$capacity" -le 10 ]; then
			notify-send -u critical -t 5000 "$low_message" "$status ${capacity}%"
		fi
	fi
}
