#!/usr/bin/env python3

import datetime as dt

time = dt.datetime(2019, 1, 17, 13, 30)
current = dt.datetime.now()
delta = time - current
if delta.days < 0 or delta.seconds < 0:
    print("time has gone")
else:
    hours = delta.seconds // 3600
    seconds = delta.seconds - hours*3600
    minutes = seconds // 60
    print(f"{hours}:{minutes}")
