#!/bin/bash

suffix="_inverted_"
wid=$(xdotool getwindowfocus)
class=$(xprop -id $wid | grep "WM_CLASS" | sed -n 's/.*"\(.*\)".*".*"$/\1/p')

if [[ "$class" =~ .*${suffix}.* ]]; then
    class="$(echo $class | sed "s/$suffix//")"
else
    class="${class}${suffix}"
fi

xdotool set_window --classname "$class" $wid
