#!/bin/bash

suffix="_inverted"
wid=$(xdotool getwindowfocus)
class=$(xprop -id $wid | grep "WM_CLASS" | sed -n 's/.*"\(.*\)".*".*"$/\1/p')

if [[ "$class" =~ .*$suffix$ ]]; then
	length=$((${#class} - ${#suffix}))
	class="${class:0:$length}"
else
	class="${class}${suffix}"
fi

xdotool set_window --classname "$class" $wid

coincidence=$(ps -eo "cmd" | \
	grep "compton.\+invert-color-include class_i" | wc -l)
if [ $coincidence -lt 2 ]; then
	pkill compton
	setsid compton --invert-color-include 'class_i%="*_inverted"' &
fi
