#!/bin/sh

# If no url given. Opens browser. For using script as $BROWSER.
# [ -z "$1" ] && { "$TRUEBROWSER"; exit; }

case "$1" in
	*youtube.com*)
		setsid mpv -quiet --ytdl-format="bestvideo[height<=1080]+bestaudio" "$1" >/dev/null 2>&1 & ;;
	*mkv|*webm|*mp4|*3gp)
		setsid mpv -quiet "$1" >/dev/null 2>&1 & ;;
	*png|*jpg|*jpe|*jpeg)
		setsid feh "$1" >/dev/null 2>&1 & ;;
	*mp3|*flac|*opus|*mp3?source)
		setsid wget "$1" >/dev/null 2>&1 & ;;
	*)
		setsid "$BROWSER" "$1" >/dev/null 2>&1 & ;;
esac
