#!/bin/bash

case "$1" in
    *youtube.com/watch*|*youtube.com/playlist*|*youtu.be*)
        notify-send "Opening" "$1"
        setsid ytstream "$1" & ;;
    *mkv|*webm|*mp4|*3gp|*avi)
        setsid mpv -quiet "$1" >/dev/null 2>&1 & ;;
    *png|*jpg|*jpe|*jpeg|*gif)
        curl -sL "$1" > "/tmp/$(echo "$1" | sed "s/.*\///")" && sxiv -a "/tmp/$(echo "$1" | sed "s/.*\///")" ;;
    *mp3|*flac|*opus|*mp3?source)
        setsid tsp wget -P "$PODCASTS" "$1" >/dev/null 2>&1 & ;;
    *)
        browser=$(sed -n '/BROWSER/s/.\+"\(.\+\)"/\1/p' ~/.profile)
        setsid "$browser" "$1" >/dev/null 2>&1 & ;;
esac
