#!/bin/sh

case "$1" in
	*youtube.com*)
		setsid ytstream "$1" & ;;
	*mkv|*webm|*mp4|*3gp|*avi)
		setsid mpv -quiet "$1" >/dev/null 2>&1 & ;;
	*png|*jpg|*jpe|*jpeg)
		setsid feh "$1" >/dev/null 2>&1 & ;;
	*gif)
		setsid mpv --loop "$1" >/dev/null 2>&1 & ;;
	*mp3|*flac|*opus|*mp3?source)
		setsid tsp wget -P "$PODCASTS" "$1" >/dev/null 2>&1 & ;;
	*)
		setsid $BROWSER $1 >/dev/null 2>&1 & ;;
esac
