#!/bin/sh

pgrep -x i3lock >/dev/null && exit

image="$HOME/Documents/lockimage"

i3lock -k --bar-indicator -e -f -c 303030 -i "$image"

if [ "$?" -eq 0 -a "$1" = "--dpms" ]; then
    sleep 1 && xset dpms force off
fi
