#!/bin/bash

filename="%Y-%m-%d_%H-%M.png"
if [ ! -z $SCREENSHOTS ]; then
	filename="$SCREENSHOTS/$filename"
fi

if [ "$1" = 'part' ]; then
	file=$(scrot -z -s -q 100 $filename -e 'echo $f')
else
	file=$(scrot -z -q 100 $filename -e 'echo $f')
fi

[ -z $file ] && exit

xclip -selection clipboard -t image/png -i "$file" && notify-send -i "$file" "Copied to clipboard"
xclip -i "$file" && notify-send "Copied to primary" "$file"
