#!/bin/sh

folders="wallpapers
screenshots
luke"

folder=$(echo -e -n "$folders" | dmenu -i -p "Choose folder:")

case $folder in
    wallpapers) sxiv -t $WALLPAPERS ;;
    screenshots) sxiv -t $SCREENSHOTS ;;
    luke) # https://github.com/LukeSmithxyz/wallpapers
        cd "$PICTURES"/luke/
        luke=$(ls -1d */ | dmenu -i -p "Choose luke folder:")
        sxiv -t "$luke"
        ;;
esac
