#!/bin/sh

options="1.shutdown\n2.reboot\n3.suspend\n4.lock\n5.hibernate"

if [ ! -z "$1" ]; then
	option="$1"
else
	option="$(echo -e $options | dmenu -i -p "Option:")"
fi

case $option in
    *reboot)    reboot ;;
    *lock)      lockscreen --dpms ;;
    *shutdown)  shutdown -h now ;;
    *suspend)   mpc pause >/dev/null 2>&1 && lockscreen && systemctl suspend ;;
    *hibernate) mpc pause >/dev/null 2>&1 && lockscreen && systemctl hibernate ;;
    *)          echo "Incorrect option" ;;
esac
