#!/bin/sh

options="1) shutdown\n2) reboot\n3) hibernate\n4) suspend\n5) lock(dmps)\n6) lock"

case $(echo -e $options | dmenu -i -p "Option:") in
	*shutdown)		shutdown -h now ;;
	*reboot)			reboot ;;
	*hibernate)		systemctl hibernate ;;
	*suspend)		systemctl suspend ;;
	*lock*dmps*)	xset dpms force off ;;
	*lock)			lockscreen ;;
esac
