#!/bin/sh

# usage: timewall [-ps|-pd]

# -ps - prevent setting new wallpaper
# -pd - prevent daemonize

time_pic="/tmp/time_left.png"
wall_pic="$HOME/Documents/wallpaper"
new_wall_pic="/tmp/wall_with_time.png"

midnight=$(date -u -d "00:00" +"%s")

border_color="brown"
text_color="orange"

walsetter() {
    current=$(date -u -d "$(date +%R)" +"%s")
    left_time="$(date -u -d "0 $midnight sec - $current sec" +"%H:%M")"

    convert -size 1920x1080 xc:none \
        -stroke $border_color -strokewidth 4 \
        -pointsize 400 -fill $text_color -gravity center \
        -draw "text 0,0 '$left_time'" \
        -trim +repage "$time_pic"

    magick composite -gravity center "$time_pic" "$wall_pic" "$new_wall_pic"

    [ "$1" != "-ps" ] && xwallpaper --stretch "$new_wall_pic"
}

if [ "$1" = "-pd" ]; then
    walsetter
else
    while true; do
        walsetter
        sleep 1m
    done
fi
